version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
      - ./services/nginx/web.conf:/etc/nginx/conf.d/web.conf
    ports:
      - 8889:80
    depends_on:
      - fpm1
      - fpm2
    networks:
      - cluster-demo
  mysql-master:
    build:
      context: .
      dockerfile: ./services/mysql/master/Dockerfile
    volumes:
      - ./services/mysql/master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql-master:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
    networks:
      - cluster-demo
  mysql-slave1:
    build:
      context: .
      dockerfile: ./services/mysql/slave1/Dockerfile
    volumes:
      - ./services/mysql/slave1/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql-slave1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    ports:
      - 33062:3306
    networks:
      - cluster-demo
  mysql-slave2:
    build:
      context: .
      dockerfile: ./services/mysql/slave2/Dockerfile
    volumes:
      - ./services/mysql/slave2/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql-slave2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    ports:
      - 33063:3306
    networks:
      - cluster-demo
  fpm1:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    volumes:
      - ./:/usr/share/nginx/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - cluster-demo
  fpm2:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    volumes:
      - ./:/usr/share/nginx/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - cluster-demo
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - ./data/redis:/data
    networks:
      - cluster-demo
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - cluster-demo
    ports:
      - 8886:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-master
networks:
  cluster-demo:
    driver: bridge