CREATE DATABASE demo;
USE demo;
CREATE TABLE posts(
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `body` TEXT NOT NULL
) ENGINE innoDB CHARSET=utf8;
CREATE TABLE users(
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE innoDB CHARSET=utf8;
INSERT INTO users (`username`, `password`) VALUE ('demo', '5f4dcc3b5aa765d61d8327deb882cf99');